[project]
name = "quantum-studies"
version = "0.1.0"
description = ""
authors = [
    {name = "Hernan Esteves",email = "hernan.esteves@codility.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "amazon-braket-sdk (>=1.91.0,<2.0.0)",
    "jupyterlab (>=4.4.0,<5.0.0)",
    "qutip (>=5.1.1,<6.0.0)",
    "plotly (>=6.0.1,<7.0.0)",
    "ipywidgets (>=8.1.5,<9.0.0)",
    "matplotlib (>=3.10.1,<4.0.0)",
    "qiskit (>=2.0.0,<3.0.0)"
]

[tool.poetry]
packages = [{include = "quantum_studies", from = "src"}]
package-mode = false


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"


