from qiskit import QuantumCircuit


qc = QuantumCircuit.from_qasm_file("/workspaces/quantum-alg/quantum-studies/src/quantum_studies/qiskit_circuits/advanced/circuit.qasm")

print(qc.draw())  # Visualize the circuit

qasm_str = """
// Generated by Qiskit
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
creg c[2];
cx q[0],q[1];
measure q[0] -> c[0];
measure q[1] -> c[1];
"""

qc_from_str = QuantumCircuit.from_qasm_str(qasm_str)
print(qc_from_str.draw())  # Visualize the circuit from QASM string